### ISSUE TITLE
SolanaTypes not found in import setence

### ISSUE THREAD

**Issue by mdfalcon104** [certusone/xdapp-book#135]
TSError: ⨯ Unable to compile TypeScript:
handlers/solana.ts:6:38 - error TS2307: Cannot find module '../chains/solana/target/types/solana' or its corresponding type declarations.

6 import { Solana as SolanaTypes} from '../chains/solana/target/types/solana';
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by evan-gray** [comment]
This repo is being archived in favor of docs.wormhole.com
